name: "Add Npm Registry"
description: "Add npm registry and token to .npmrc"
inputs:
  registry:
    description: "Npm Registry"
    required: false
    default: "npm.pkg.github.com"
  authToken:
    description: "Npm Auth Token"
    required: true
  path:
    description: "Path to .npmrc"
    required: false
    default: ".npmrc"
runs:
  using: composite
  steps:
  - shell: bash
    run: |
      echo "//${{ inputs.registry }}/:_authToken=${{ inputs.authToken }}" >> ${{ inputs.path }}
